INTRODUCTION TO MACHINE LEARNING WITH PYTHON

DATA TYPES & *STRUCTURES*

In [73]:
MIDE = {"name": "MIDE", "AGE": 14} #dictionary has two notations: keys, values
MIDE = [1, 2, 3, 4] #list
khan_1 = (1, 2, 3, 4, 5) #tuple
khan2 = 1; #integer
khan_3 = "captain" #string
khan_4 = 5.0 #float
khan_5 = True #boolean
khan_6 = {1, 2, 4, 6} #set
khan_7 = "c-a-p-t"

In [74]:
#To check for the type of an object or variable, use type{}
type(khan_4)

float

TYPE CASTING / CONVERSION

In [75]:
type(str(khan2))

str

BASIC OPERATIONS: PEMDAS

In [76]:
sum([1,1])

2

In [77]:
a = 5
b = 5
print(a+b) #addition
print(a-b) #subtraction
print(a/b) #division
print(a*b) #multiplication

10
0
1.0
25

Conditional statements & For loop

In [78]:
"""
if type(khan_3) == int:
  print("MIDE NO GET SENSE")
else:
    print("MIDE IS A GIRL")
"""

#for loop allows iteration over sequence or list of values/objects
for i in MIDE:
      print(i+2)

3
4
5
6

LIST COMPREHENSION: ONE OF THE METHODS THAT ENSURES OPTIMIZED MACHINE LEARNING TRAINING

In [79]:
#extract the even numbers from the khan list
even_number_list = []
odd_number_list = []
for i in MIDE:
  if i % 2 ==0:
    even_number_list.append(i) #append is a method that adds aan element or value to an existing list
  else:
    odd_number_list.append(i)

#print(odd_number_list)
#print(even_number_list)



#LIST COMPREHENSION
even_mumber_list2 = [i for i in MIDE if i % 2 == 0]
odd_number_list2 = [i for i in MIDE if i % 2 != 0]

print(odd_number_list)
print(even_number_list)

[1, 3]
[2, 4]

BRIEF: OBJECT ORIENTED PROGRAMME

In [80]:
khan_7.split("-")

['c', 'a', 'p', 't']

In [81]:
#defining a function
def AREA(l, h= 50):
  #l = LENGTH
  #H = HEIGHT
  return l*h

AREA(2, h=100)

200

In [82]:
class Swep():
  def __init__(self, uni, level, dept, count = 47): #number of students = 47
    self.uni = uni
    self.level = level
    self.dept = dept
    self.count = count

  def product_of_student_count_with_length_of_uni(self): #method, belongs to class
    product = self.count * self.level
    return product

uni = "OAU"
level = 250
dept = "CHE"

#STEP1: INITIALIZE THE CLASS
swep = Swep(uni, level, dept)

#step2: PERFORM THE ACTION: to perform an operation under a clas, use the dot notation, for example initialie class.method)
swep.product_of_student_count_with_length_of_uni()

11750

LOADING A DATASET WITH PYTHON USING PANDA

In [83]:
import pandas as pd
"""

panda is a python library for loading datasets,
and performing explorator data analysis,
 which include data processinf, data transformation,
data wranging, etc.
"""

#load the dataset
df = pd.read_csv("/content/AI_SocialMedia_Student_Health_Dataset_clean.csv")
df

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Burnout_Level,Academic_Performance_Score,Academic_Failure_Risk
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90,4.05,Low,88.80,0
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94,4.65,Moderate,50.60,0
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75,5.28,Low,96.67,0
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38,3.66,Low,85.65,0
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04,3.25,Moderate,71.84,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,STU_14996,18,Non-binary,College,6.10,0.72,5.63,0.89,74.08,71.92,3.78,Moderate,77.43,0
14996,STU_14997,22,Female,University,4.55,1.20,7.20,0.00,73.72,85.84,5.06,Low,75.81,0
14997,STU_14998,13,Male,High School,7.83,1.46,6.22,0.64,70.03,86.62,4.76,Moderate,89.84,0
14998,STU_14999,20,Female,College,6.99,3.00,4.24,1.97,57.38,85.34,2.82,Severe,65.44,1
14999,STU_15000,14,Male,High School,3.73,3.03,6.39,1.50,71.69,78.62,4.37,Moderate,92.91,0

.head() by default returns the first five rows. .tail() by default returns the last 5 rows
.describe() provides statistical output

In [84]:
df.head()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Burnout_Level,Academic_Performance_Score,Academic_Failure_Risk
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90,4.05,Low,88.80,0
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94,4.65,Moderate,50.60,0
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75,5.28,Low,96.67,0
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38,3.66,Low,85.65,0
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04,3.25,Moderate,71.84,0

In [85]:
df.tail()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Burnout_Level,Academic_Performance_Score,Academic_Failure_Risk
14995,STU_14996,18,Non-binary,College,6.10,0.72,5.63,0.89,74.08,71.92,3.78,Moderate,77.43,0
14996,STU_14997,22,Female,University,4.55,1.20,7.20,0.00,73.72,85.84,5.06,Low,75.81,0
14997,STU_14998,13,Male,High School,7.83,1.46,6.22,0.64,70.03,86.62,4.76,Moderate,89.84,0
14998,STU_14999,20,Female,College,6.99,3.00,4.24,1.97,57.38,85.34,2.82,Severe,65.44,1
14999,STU_15000,14,Male,High School,3.73,3.03,6.39,1.50,71.69,78.62,4.37,Moderate,92.91,0

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  15000 non-null  object
 1   Age                         15000 non-null  int64
 2   Gender                      15000 non-null  object
 3   Education_Level             15000 non-null  object
 4   Daily_Social_Media_Hours    15000 non-null  float64
 5   Daily_AI_Tool_Usage_Hours   15000 non-null  float64
 6   Sleep_Hours                 15000 non-null  float64
 7   Physical_Activity_Hours     15000 non-null  float64
 8   Mental_Health_Score         15000 non-null  float64
 9   Physical_Health_Score       15000 non-null  float64
 10  Social_Isolation_Score      15000 non-null  float64
 11  Burnout_Level               15000 non-null  object
 12  Academic_Performance_Score  15000 non-null  float64
 13  Academic_Failure_Risk       15000 non-null  int64
dtypes: float64(8), int64(2), object(4)
memory usage: 1.6+ MB

In [87]:
df.describe()

,Age,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Academic_Performance_Score,Academic_Failure_Risk
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,19.040667,4.537500,2.584580,6.544205,1.246332,72.513156,88.019761,4.312027,78.314859,0.060000
std,3.767257,2.398494,1.677988,1.269770,1.038349,9.245482,9.684253,1.162432,11.544651,0.237495
min,13.000000,0.000000,0.000000,2.000000,0.000000,32.560000,48.030000,0.970000,23.990000,0.000000
25%,16.000000,2.830000,1.310000,5.680000,0.310000,66.780000,81.520000,3.470000,70.530000,0.000000
50%,19.000000,4.500000,2.510000,6.550000,1.130000,73.760000,89.470000,4.280000,78.590000,0.000000
75%,22.000000,6.180000,3.740000,7.410000,1.950000,79.580000,97.160000,5.120000,86.700000,0.000000
max,25.000000,14.000000,9.500000,11.150000,5.000000,91.760000,99.980000,8.410000,99.980000,1.000000

In [88]:
df.drop("Student_ID", axis=1, inplace=True) #setting axis to 1 means point to columns

In [89]:
df

,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score,Social_Isolation_Score,Burnout_Level,Academic_Performance_Score,Academic_Failure_Risk
0,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90,4.05,Low,88.80,0
1,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94,4.65,Moderate,50.60,0
2,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75,5.28,Low,96.67,0
3,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38,3.66,Low,85.65,0
4,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04,3.25,Moderate,71.84,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,18,Non-binary,College,6.10,0.72,5.63,0.89,74.08,71.92,3.78,Moderate,77.43,0
14996,22,Female,University,4.55,1.20,7.20,0.00,73.72,85.84,5.06,Low,75.81,0
14997,13,Male,High School,7.83,1.46,6.22,0.64,70.03,86.62,4.76,Moderate,89.84,0
14998,20,Female,College,6.99,3.00,4.24,1.97,57.38,85.34,2.82,Severe,65.44,1
14999,14,Male,High School,3.73,3.03,6.39,1.50,71.69,78.62,4.37,Moderate,92.91,0

In [92]:
df.to_csv("swep.csv", index=False)